-- VER BASES DE DATOS EN EL SERVIDOR
SHOW databases;

-- SELECCIONAR UNA BASE DE DATOS
USE nombreBaseDatos;

-- VER TABLAS DE LA BASE DE DATOS
SHOW TABLES;

-- VER INFORMACION DE LA TABLA
DESCRIBE nombreTabla;
